---
name: Lint (YAML)
on:  # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths: ["**.ya?ml"]

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c  # tag=v3.1.1
        with:
          format: github
          config_data: '{extends: default, ignore: "**/templates/*.yaml", rules: {line-length: {max: 240}, comments: {min-spaces-from-content: 1}}}'
          strict: true
