---
name: Lint (NodeJS/Typescript)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths: ["src/kubeapps-components/**/*"]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 18
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Install dependencies
        run: yarn install
        working-directory: src/kubeapps-components
      - name: Run ESLint
        run: yarn lint:ci src/
        working-directory: src/kubeapps-components
        continue-on-error: true
      - uses: ataylorme/eslint-annotate-action@a1bf7cb320a18aa53cb848a267ce9b7417221526 # tag=v1.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          report-json: src/kubeapps-components/eslint_report.json
          fail-on-warning: true

  codeql:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: github/codeql-action/init@579411fb6c2fa885902ffeb0238873661aa2dc29 # tag=codeql-bundle-20221024
        with:
          languages: javascript
      - uses: github/codeql-action/autobuild@579411fb6c2fa885902ffeb0238873661aa2dc29 # tag=codeql-bundle-20221024
      - uses: github/codeql-action/analyze@579411fb6c2fa885902ffeb0238873661aa2dc29 # tag=codeql-bundle-20221024
