---
name: Release Belug-Apps (Manual)
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      type:
        description: Is a MAJOR, MINOR or PATCH release?
        required: true
        type: choice
        options:
          - pre-release
          - patch
          - minor
          - major
      dryRun:
        description: Run the workflow without creating any release?
        default: false
        type: boolean

concurrency:
  cancel-in-progress: true
  group: manual-release-workflow

jobs:
  bump_version:
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.semver-pre.outputs.next || steps.semver.outputs.next }}
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          # NOTE: fetch all commits and tags
          fetch-depth: "0"

      - uses: asdf-vm/actions/setup@707e84f3ee349548310aeabdad0dd3bfcb9b69fa # v1.1.0
      - uses: actions/cache@58c146cc91c5b9e778e71775dfe9bf1442ad9a12 # v3.2.3
        with:
          path: ${{ env.ASDF_DIR }}
          key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
          restore-keys: |
            ${{ runner.os }}-asdf-
      - uses: asdf-vm/actions/install@707e84f3ee349548310aeabdad0dd3bfcb9b69fa # v1.1.0

      - name: Bump version to the next ${{ inputs.type }}
        if: inputs.type == 'pre-release'
        id: semver-pre
        run: |
          tag="$(git tag --sort=-v:refname | head --lines=1)"
          echo "::debug::tags found: $(git tag --sort=-v:refname | xargs)"
          echo "::debug::latest tag: ${tag}"

          # NOTE: if no RC are found, we will create a new one based on the next minor
          #       release
          grep -- '-rc' <<<"${tag}" > /dev/null || tag="$(semver bump minor "${tag}")"
          echo "::debug::tag after transformation: ${tag}"

          echo >> "${GITHUB_OUTPUT}" "next=$(semver bump prerel rc.. "${tag}")"

      - name: Bump version to the next ${{ inputs.type }}
        if: inputs.type != 'pre-release'
        id: semver
        run: |
          tag="$(git tag --sort=-v:refname | grep --invert-match -- '-rc' | head --lines=1)"
          echo "::debug::tags found: $(git tag --sort=-v:refname | xargs)"
          echo "::debug::latest tag: ${tag}"

          echo >> "${GITHUB_OUTPUT}" "next=$(semver bump ${{ inputs.type }} "${tag}")"

  release:
    uses: ./.github/workflows/release.workflow.yml
    needs: [bump_version]
    with:
      version: ${{ needs.bump_version.outputs.release_version }}
      ref: ${{ github.ref_name }}
      dryRun: ${{ inputs.dryRun }}
    secrets: inherit
