---
name: Release Belug-Apps (Workflow)
on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      version:
        description: Release version.
        required: true
        type: string
      ref:
        description: The branch, tag or SHA to release.
        default: main
        type: string
      dryRun:
        description: Run the workflow without creating any release?
        default: false
        type: boolean

concurrency:
  cancel-in-progress: true
  group: release-workflow

jobs:
  build_image:
    name: Release `ghcr.io/belug-apps/api-proxy` (v${{ inputs.version }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # tag=v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe311567a96 # v4.3.0
        id: meta
        with:
          images: ghcr.io/belug-apps/api-proxy
          tags: ${{ inputs.version }}
          labels: |
            org.opencontainers.image.title=Belug-Apps API proxy
            org.opencontainers.image.description=Proxy allowing access to APIs such as TrueNAS without authentication but limiting access only to what is needed.

          bake-target: belug-apps_api-proxy
      - uses: docker/bake-action@6c87dcca988e4e074e3ab1f976a70f63ec9673fb # tag=v2.3.0
        with:
          workdir: src/api-proxy/
          files: ${{ steps.meta.outputs.bake-file }}
          targets: belug-apps_api-proxy
          push: ${{ ! inputs.dryRun }}

  update_repo:
    name: Update `belug-apps` repository (v${{ inputs.version }})
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@021a2405c7f990db57f5eae5397423dcc554159c # tag=1.7.0
        id: app_auth
        with:
          app_id: ${{ secrets.BOT_ID }}
          private_key: ${{ secrets.BOT_PKEY }}

      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}
          token: ${{ steps.app_auth.outputs.token }}

      - uses: asdf-vm/actions/setup@707e84f3ee349548310aeabdad0dd3bfcb9b69fa # v1.1.0
      - uses: actions/cache@58c146cc91c5b9e778e71775dfe9bf1442ad9a12 # v3.2.3
        with:
          path: ${{ env.ASDF_DIR }}
          key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
          restore-keys: |
            ${{ runner.os }}-asdf-
      - uses: asdf-vm/actions/install@707e84f3ee349548310aeabdad0dd3bfcb9b69fa # v1.1.0

      - run: just release ${{ inputs.version }}

      # NOTE: commit all changes
      - uses: EndBug/add-and-commit@61a88be553afe4206585b31aa72387c64295d08b # tag=v9.1.1
        with:
          author_name: belug-apps[bot]
          author_email: 116495032+belug-apps[bot]@users.noreply.github.com
          message: ":bookmark: release Belug-Apps v${{ inputs.version }}"
          push: ${{ ! inputs.dryRun }}
          tag: v${{ inputs.version }}
