---
name: Release Belug-Apps (Release Tag)
on: # yamllint disable-line rule:truthy
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  github_release:
    name: Create a Github release for ${{ github.ref_name }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # tag=v0.1.15
        # NOTE: the current `softprops/action-gh-release` is bugged; it creates the releases but
        #       fails just after
        continue-on-error: true
        with:
          discussion_category_name: 🔖 ${{ github.ref_name }}
          generate_release_notes: true
      - run: echo "::debug::Release successfully created... although the previous steps failed"

  sync_catalog:
    name: Sync `belug-apps/truecharts-catalog` with ${{ github.ref_name }} release
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: tibdex/github-app-token@021a2405c7f990db57f5eae5397423dcc554159c # tag=1.7.0
        id: app_auth
        with:
          app_id: ${{ secrets.BOT_ID }}
          private_key: ${{ secrets.BOT_PKEY }}

      - uses: peter-evans/repository-dispatch@26b39ed245ab8f31526069329e112ab2fb224588 # v2.1.1
        with:
          client-payload: '{"ref":"${{ github.ref_name }}","train":"stable"}'
          event-type: sync-belugapps
          repository: belug-apps/truecharts-catalog
          token: ${{ steps.app_auth.outputs.token }}
