---
name: Security (Docker)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths: ["src/api-proxy/Dockerfile"]
  push:
    branches: [main]

jobs:
  check_docker_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - uses: docker/metadata-action@57396166ad8aefe6098280995947635806a0e6ea # tag=v4.1.1
        id: meta
        with:
          bake-target: belug-apps_api-proxy
          labels: |
            org.opencontainers.image.title=Belug-Apps API proxy
            org.opencontainers.image.description=Proxy allowing BelugApps to access APIs such as TrueNAS without authentication and in a secure way
          images: ghcr.io/belug-apps/api-proxy
          tags: snyk-${{ github.run_id }}

      - uses: docker/bake-action@6c87dcca988e4e074e3ab1f976a70f63ec9673fb # tag=v2.3.0
        with:
          files: ${{ steps.meta.outputs.bake-file }}
          workdir: src/api-proxy/
          targets: belug-apps_api-proxy
          load: true

      - uses: snyk/actions/docker@7fad562681122205233d1242c3bb39598c5393da # tag=0.3.0
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ghcr.io/belug-apps/api-proxy:snyk-${{ github.run_id }}
          args: --file=./src/api-proxy/Dockerfile
      - uses: github/codeql-action/upload-sarif@32be38eeffb2f4ae668081106bdd999e1f786b3d # tag=codeql-bundle-20221024
        with:
          sarif_file: snyk.sarif
