---
name: Security (Docker)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths: ["src/api-proxy/Dockerfile"]
  push:
    branches: [main]

jobs:
  check_docker_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - uses: docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe311567a96 # v4.3.0
        id: meta
        with:
          bake-target: belug-apps_api-proxy
          labels: |
            org.opencontainers.image.title=Belug-Apps API proxy
            org.opencontainers.image.description=Proxy allowing BelugApps to access APIs such as TrueNAS without authentication and in a secure way
          images: ghcr.io/belug-apps/api-proxy
          tags: snyk-${{ github.run_id }}

      - uses: docker/bake-action@6c87dcca988e4e074e3ab1f976a70f63ec9673fb # tag=v2.3.0
        with:
          files: ${{ steps.meta.outputs.bake-file }}
          workdir: src/api-proxy/
          targets: belug-apps_api-proxy
          load: true

      - uses: snyk/actions/docker@7fad562681122205233d1242c3bb39598c5393da # tag=0.3.0
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ghcr.io/belug-apps/api-proxy:snyk-${{ github.run_id }}
          args: --file=./src/api-proxy/Dockerfile
      - uses: github/codeql-action/upload-sarif@579411fb6c2fa885902ffeb0238873661aa2dc29 # tag=codeql-bundle-20221024
        with:
          sarif_file: snyk.sarif
